# Generated by Django 3.2 on 2021-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackchairprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trackchairprofile',
            name='prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trackchairprofile',
            name='track',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
