# Generated by Django 3.2 on 2021-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackchairprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trackchairprofile',
            name='prefix',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
