# Generated by Django 3.2 on 2021-06-16 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('track', models.CharField(max_length=500)),
                ('prefix', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, default='2', max_length=1)),
                ('status_A', models.CharField(blank=True, default='2', max_length=1)),
                ('status_B', models.CharField(blank=True, default='2', max_length=1)),
                ('remark', models.CharField(blank=True, default='', max_length=5000)),
                ('remark_A', models.CharField(blank=True, default='', max_length=5000)),
                ('remark_B', models.CharField(blank=True, default='', max_length=5000)),
                ('track_A', models.CharField(blank=True, default='A', max_length=5000, null=True)),
                ('track_B', models.CharField(blank=True, default='admin', max_length=5000, null=True)),
                ('country', models.CharField(blank=True, default='undefined', max_length=5000, null=True)),
                ('state', models.CharField(blank=True, default='undefined', max_length=500, null=True)),
                ('institution', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='[0-9]{10}')])),
                ('paper_title', models.CharField(max_length=500)),
                ('paper_pdf', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('submission_date', models.DateTimeField()),
                ('abstract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.abstract', verbose_name='Abstract')),
            ],
        ),
    ]
