# Generated by Django 3.2 on 2021-06-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_abstract_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='institution',
            field=models.CharField(max_length=500),
        ),
    ]
