# Generated by Django 3.2 on 2021-04-12 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_alter_paper_paper_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(max_length=500),
        ),
    ]
