# Generated by Django 3.2 on 2021-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20210616_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ppt_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_count', models.IntegerField(default=0)),
            ],
        ),
    ]
