# Generated by Django 3.2 on 2021-06-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_ppt_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppt_count',
            old_name='paper_count',
            new_name='ppt_count',
        ),
    ]
