# Generated by Django 3.2 on 2021-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_alter_abstract_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='country',
            field=models.CharField(blank=True, default='undefined', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='institution',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='paper_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='remark_A',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='remark_B',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='track_A',
            field=models.CharField(blank=True, default='A', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='track_B',
            field=models.CharField(blank=True, default='admin', max_length=5000, null=True),
        ),
    ]
