# Generated by Django 3.2 on 2021-06-16 22:36

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_rename_paper_count_ppt_count_ppt_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='abstract_affiliation_pdf',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='abstract_pdf',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
