# Generated by Django 3.2 on 2021-06-14 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20210613_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Type',
            fields=[
                ('author_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, default='unknown', max_length=100)),
                ('track', models.CharField(max_length=500)),
                ('prefix', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_id_approved', models.BooleanField(blank=True, default=False)),
                ('is_payment_approved', models.BooleanField(blank=True, default=False)),
                ('country', models.CharField(blank=True, default='undefined', max_length=5000, null=True)),
                ('state', models.CharField(blank=True, default='undefined', max_length=500, null=True)),
                ('institution', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='[0-9]{10}')])),
                ('registration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Type',
            fields=[
                ('registration_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
