# Generated by Django 3.2 on 2021-05-04 13:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_pdf',
        ),
        migrations.AddField(
            model_name='paper',
            name='abstract_pdf',
            field=models.FileField(default=django.utils.timezone.now, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
            preserve_default=False,
        ),
    ]
