# Generated by Django 3.2 on 2021-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_author_type_registration_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_type',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration_type',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author_type',
            name='author_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration_type',
            name='registration_type',
            field=models.CharField(max_length=100),
        ),
    ]
