# Generated by Django 3.2 on 2021-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_auto_20210614_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
