# Generated by Django 3.2 on 2021-05-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_rename_paper_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='keywords',
        ),
    ]
