# Generated by Django 3.2 on 2021-06-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_alter_registration_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='remark_C',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='abstract',
            name='status_C',
            field=models.CharField(blank=True, default='2', max_length=1),
        ),
    ]
