# Generated by Django 3.2 on 2021-06-15 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20210614_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='abstract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.abstract', verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='registration',
            name='author_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.author_type', verbose_name='Author_Type'),
        ),
        migrations.AddField(
            model_name='registration',
            name='id_proof',
            field=models.FileField(blank=True, default='undefined', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', validators=[django.core.validators.FileExtensionValidator(['png', 'pdf', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.registration_type', verbose_name='Registration_Type'),
        ),
    ]
