# Generated by Django 3.2 on 2021-05-11 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_remove_abstract_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='track',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
