# Generated by Django 3.2 on 2021-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20210615_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_Paper_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_paper_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
