# Generated by Django 3.2 on 2021-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_abstract_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_count', models.IntegerField(default=0)),
            ],
        ),
    ]
