# Generated by Django 3.2 on 2021-05-12 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_paper_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='id',
        ),
        migrations.AddField(
            model_name='abstract',
            name='abs_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
