# Generated by Django 3.2 on 2021-06-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_auto_20210615_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='track',
        ),
    ]
