# Generated by Django 3.2 on 2021-06-24 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_auto_20210625_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinfo',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='pending_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receivedexception',
            name='exception_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
