# Generated by Django 3.2 on 2021-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_remove_registration_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
    ]
