# Generated by Django 3.2 on 2021-06-26 20:47

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20210625_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id_proof',
            field=models.FileField(blank=True, default='undefined', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', validators=[django.core.validators.FileExtensionValidator(['png', 'pdf', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
