# Generated by Django 3.2 on 2021-07-03 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20210627_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Receipt', serialize=False, to='conference.registration', verbose_name='Registration')),
                ('receipt_file', models.FileField(blank=True, default='undefined', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='receipts', validators=[django.core.validators.FileExtensionValidator(['png', 'pdf', 'jpeg', 'jpg'])])),
            ],
        ),
        migrations.AlterField(
            model_name='abstract',
            name='abs_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='phone',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='prefix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='phone',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='prefix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='phone',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='ppt_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='prefix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
