# Generated by Django 3.2 on 2021-06-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20210615_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='author_type',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_type',
        ),
    ]
