# Generated by Django 3.2 on 2021-06-29 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20210627_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(blank=True, default='undefined', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='receipts', validators=[django.core.validators.FileExtensionValidator(['png', 'pdf', 'jpeg', 'jpg'])])),
                ('registration_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.registration', verbose_name='Registration')),
            ],
        ),
    ]
