# Generated by Django 3.2 on 2021-06-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_receipts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipts',
            new_name='Receipt',
        ),
    ]
