# Generated by Django 3.2 on 2021-06-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_rename_receipts_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='registration_id',
            new_name='registration',
        ),
    ]
