# Generated by Django 3.2 on 2021-06-30 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_rename_registration_id_receipt_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='id',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='registration',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Receipt', serialize=False, to='conference.registration', verbose_name='Registration'),
            preserve_default=False,
        ),
    ]
