# Generated by Django 3.2 on 2021-07-01 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_auto_20210630_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_to', models.CharField(blank=True, default='unknown', max_length=500)),
                ('name', models.CharField(blank=True, default='unknown', max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(blank=True, default='unknown', max_length=50000)),
                ('institution', models.CharField(blank=True, default='unknown', max_length=10000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
