# Generated by Django 3.2 on 2021-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='abstract_url',
            field=models.CharField(blank=True, default='unknown', max_length=5000),
        ),
    ]
